### ISSUE TITLE
upon "resume" answers reset to 0

### ISSUE THREAD

**Issue by dquentel** [CCALI/CALI-Author-Viewer-5#104] opened 2018-10-15 20:49 UTC
From student comment via Google doc. 

9/29/2018 13:15:45 | Hello.  I love CALI's new look, as I reviewed it a few weeks back. But, today I realized a new glitch of sorts:  Even though my Lesson Runs are being saved, when I try to resume a lesson, my Right and Wrong answers each return to 0. |   | EVD16 | About this lesson | isabela_g | Isabela Goncalves | Albany Law School | 06/05/2012 | 11913040 |

**Comment by emasters** [comment] 2018-10-15 21:04
This was fixed 10 days ago. Duplicate of https://github.com/CCALI/drupal7-cali/issues/502.

**Closed by emasters** 2018-10-15 21:04 UTC
